=== nathalie-megevand/SER-2019/Echecs.dtd
<!ELEMENT FSE (Tournoi+)>
<!ELEMENT Tournoi (NomTournoi, Participant+, Vainqueur, Parties?)>
<!ELEMENT NomTournoi (#PCDATA)>
<!ELEMENT Participant (Nom, Prenom, ELO)>
    <!ATTLIST Participant id ID #REQUIRED>
    <!ELEMENT Nom (#PCDATA)>
    <!ELEMENT Prenom (#PCDATA)>
    <!ELEMENT ELO (#PCDATA)>
<!ELEMENT Vainqueur ANY>
    <!ATTLIST Vainqueur id IDREF #REQUIRED>
<!ELEMENT Parties (Partie*)>
    <!ELEMENT Partie (Date, Arbitre, Score, Blanc, Noir, Coups)>      
        <!ATTLIST Partie score (1-0 | 0.5-0.5 | 0-1) #REQUIRED>
        <!ELEMENT Date (Jour, Mois, Annee)>
            <!ELEMENT Jour (#PCDATA)>
            <!ELEMENT Mois (#PCDATA)>
            <!ELEMENT Annee (#PCDATA)>
            <!ELEMENT Heure (#PCDATA)>
            <!ELEMENT Minute (#PCDATA)>
        <!ELEMENT Arbitre (Nom, Prenom)>
        <!ELEMENT Blanc ANY>
            <!ATTLIST Blanc id IDREF #REQUIRED>
        <!ELEMENT Noir ANY>
            <!ATTLIST Noir id IDREF #REQUIRED>
        <!ELEMENT Coups (Coup*)>
            <!ELEMENT Coup (Roque | Deplacement)>
                <!ELEMENT Roque EMPTY>
                    <!ATTLIST Roque Type (Petit | Grand) #REQUIRED>
                <!ELEMENT Deplacement (Piece, Destination, Depart?, Elimination?, Promotion?, Situation?)>
                    <!ATTLIST Deplacement Piece (Tour | Cavalier | Fou | Dame | Roi | Pion) #IMPLIED>
                    <!ATTLIST Deplacement Elimination (Tour | Cavalier | Fou | Dame | Pion) #IMPLIED>
                    <!ATTLIST Deplacement Promotion (Tour | Cavalier | Fou | Dame) #IMPLIED>
                    <!ATTLIST Deplacement Situation (Échec au roi | Échec et mat | Partie nulle) #IMPLIED>
                    <!ELEMENT Destination (#PCDATA)>
                    <!ELEMENT Depart (#PCDATA)>

=== nathalie-megevand/SER-2019/Echecs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FSE SYSTEM "Echecs.dtd"> 
<FSE>
    <Tournoi>
      <NomTournoi>Tournoi dee juniors Suisse</NomTournoi>
      <Participant id="P1">
            <Nom>Turing</Nom>
            <Prenom>Alan</Prenom>
            <ELO>2700</ELO>
      </Participant>
      <Participant id="P2">
          <Nom>Lovelace</Nom>
          <Prenom>Adda</Prenom>
          <ELO>2600</ELO>
      </Participant>
        <Vainqueur id="P1"/>
        <Parties>
            <Partie score="1-0">
                <Date>
                    <Jour>07</Jour>
                    <Mois>06</Mois>
                    <Annee>2018</Annee>
                    <Heure>11</Heure>
                    <Minute>00</Minute>
                </Date>
                <Arbitre>
                    <Nom>Donald</Nom>
                    <Prenom>Knuth</Prenom>
                </Arbitre>
                <Blanc id="P1"/>
                <Noir id="P2"/>
                <Coups>
                   <Coup>
                        <Deplacement Piece="Pion">
                            <Destination>E4</Destination>
                        </Deplacement>
                   </Coup>
                   <Coup>
                        <Deplacement Piece="Pion">
                            <Destination>E5</Destination>
                        </Deplacement>
                   </Coup>
                   <Coup>
                        <Deplacement Piece="Fou">
                            <Destination>C4</Destination>
                        </Deplacement>
                   </Coup>
                   <Coup>
                        <Deplacement Piece="Cavalier">
                            <Destination>C6</Destination>
                        </Deplacement>
                   </Coup>
                   <Coup>
                        <Deplacement Piece="Dame">
                            <Destination>H5</Destination>
                        </Deplacement>
                   </Coup>
                   <Coup>
                        <Deplacement Piece="Cavalier">
                            <Destination>F6</Destination>
                        </Deplacement>
                   </Coup>
                   <Coup>
                        <Deplacement Piece="Dame"  Elimination="Pion" Situation="Ã‰chec et mat">
                            <Destination>F7</Destination>
                        </Deplacement>
                    </Coup>
                </Coups>
            </Partie>
        </Parties>
    </Tournoi>
</FSE>
